## This file contains files/sysupgrade scripts that should be preserved across
## sysupgrade so the root resize keeps working after re-flashing.
/etc/uci-defaults/70-rootpt-resize
/etc/uci-defaults/80-rootfs-resize
